//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.5.1")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_3u0a3yvi {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_3u0a3yvi() {
        }
        
        static object Create_ASP_admin_outstandingreport_aspx() {
            return new ASP.admin_outstandingreport_aspx();
        }
        
        static object Create_ASP_admin_addopenorder_aspx() {
            return new ASP.admin_addopenorder_aspx();
        }
        
        static object Create_ASP_admin_purchasereport_aspx() {
            return new ASP.admin_purchasereport_aspx();
        }
        
        static object Create_ASP_admin_reportaccount_aspx() {
            return new ASP.admin_reportaccount_aspx();
        }
    }
}
