//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.5.1")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_04u0qavm {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_04u0qavm() {
        }
        
        static object Create_ASP_admin_lasercutting_aspx() {
            return new ASP.admin_lasercutting_aspx();
        }
        
        static object Create_ASP_admin_userauthorization_aspx() {
            return new ASP.admin_userauthorization_aspx();
        }
        
        static object Create_ASP_admin_powdercoating_aspx() {
            return new ASP.admin_powdercoating_aspx();
        }
        
        static object Create_ASP_admin_departmentwisereport_aspx() {
            return new ASP.admin_departmentwisereport_aspx();
        }
        
        static object Create_ASP_admin_quotation_aspx() {
            return new ASP.admin_quotation_aspx();
        }
    }
}
