//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.5.1")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_xajlppm0 {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_xajlppm0() {
        }
        
        static object Create_ASP_admin_completedoadepartmentwiserpt_aspx() {
            return new ASP.admin_completedoadepartmentwiserpt_aspx();
        }
        
        static object Create_ASP_admin_cncbending_aspx() {
            return new ASP.admin_cncbending_aspx();
        }
        
        static object Create_ASP_admin_finalassembly_aspx() {
            return new ASP.admin_finalassembly_aspx();
        }
        
        static object Create_ASP_admin_orderacceptancelist_aspx() {
            return new ASP.admin_orderacceptancelist_aspx();
        }
        
        static object Create_ASP_admin_proformainvoice_aspx() {
            return new ASP.admin_proformainvoice_aspx();
        }
    }
}
