//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.5.1")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_z0kr4hqd {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_z0kr4hqd() {
        }
        
        static object Create_ASP_admin_pcdnotepdf_aspx() {
            return new ASP.admin_pcdnotepdf_aspx();
        }
        
        static object Create_ASP_admin_deliverychallanpdf_aspx() {
            return new ASP.admin_deliverychallanpdf_aspx();
        }
        
        static object Create_ASP_admin_creditdebitnotepdf_aspx() {
            return new ASP.admin_creditdebitnotepdf_aspx();
        }
        
        static object Create_ASP_admin_salesmasterpage_master() {
            return new ASP.admin_salesmasterpage_master();
        }
        
        static object Create_ASP_admin_salesquotationrptpdf_aspx() {
            return new ASP.admin_salesquotationrptpdf_aspx();
        }
        
        static object Create_ASP_admin_paymentpdf_aspx() {
            return new ASP.admin_paymentpdf_aspx();
        }
    }
}
