#pragma checksum "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9C59B13FE66A41C08F09199546B6F01C39FA56CF"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Login : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 86 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtemail;
    
    #line default
    #line hidden
    
    
    #line 87 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
    
    #line default
    #line hidden
    
    
    #line 92 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtpassword;
    
    #line default
    #line hidden
    
    
    #line 93 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
    
    #line default
    #line hidden
    
    
    #line 97 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    protected global::System.Web.UI.WebControls.Label lblmsg;
    
    #line default
    #line hidden
    
    
    #line 102 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    protected global::System.Web.UI.WebControls.CheckBox chkremember;
    
    #line default
    #line hidden
    
    
    #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    protected global::System.Web.UI.WebControls.Button btnlogin;
    
    #line default
    #line hidden
    
    
    #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 330 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 86 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 86 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 86 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 86 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 86 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class login_aspx : global::Login, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.login_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public login_aspx() {
            string[] dependencies;
            
            #line 912304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Login.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.login_aspx.@__initialized == false)) {
                dependencies = new string[2];
                dependencies[0] = "~/Login.aspx";
                dependencies[1] = "~/Login.aspx.cs";
                global::ASP.login_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.login_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n    <" +
                    "title>Login - Excel Enclosure</title>\r\n\r\n    <meta charset=\"utf-8\" />\r\n    <meta" +
                    " name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0" +
                    ", minimal-ui\" />\r\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n " +
                    "   <!-- Google font-->\r\n    <link href=\"https://fonts.googleapis.com/css?family=" +
                    "Open+Sans:400,600,800\" rel=\"stylesheet\" />\r\n    <!-- Required Fremwork -->\r\n    " +
                    "<link rel=\"stylesheet\" type=\"text/css\" href=\"..\\files\\bower_components\\bootstrap" +
                    "\\css\\bootstrap.min.css\" />\r\n    <!-- themify-icons line icon -->\r\n    <link rel=" +
                    "\"stylesheet\" type=\"text/css\" href=\"..\\files\\assets\\icon\\themify-icons\\themify-ic" +
                    "ons.css\" />\r\n    <!-- ico font -->\r\n    <link rel=\"stylesheet\" type=\"text/css\" h" +
                    "ref=\"..\\files\\assets\\icon\\icofont\\css\\icofont.css\" />\r\n    <!-- Style.css -->\r\n " +
                    "   <link rel=\"stylesheet\" type=\"text/css\" href=\"..\\files\\assets\\css\\style.css\" /" +
                    ">\r\n    <style>\r\n\r\n        .login-block {\r\n            /*background:none;*/\r\n    " +
                    "        /*background-color: #808080 !important;*/\r\n        }\r\n\r\n        .multicl" +
                    "r {\r\n            background: #30bab6;\r\n            background: -webkit-linear-gr" +
                    "adient(top, #163a8c, #369469);\r\n            /*background: -o-linear-gradient(top" +
                    ", #009efd, #2af598);\r\n            background: -moz-linear-gradient(top, #009efd," +
                    " #2af598);\r\n            background: linear-gradient(top, #009efd, #2af598);*/\r\n " +
                    "       }\r\n    </style>\r\n     <script src=\"https://cdn.jsdelivr.net/npm/sweetaler" +
                    "t2@10.10.1/dist/sweetalert2.all.min.js\"></script>\r\n    <link rel=\'stylesheet\' hr" +
                    "ef=\'https://cdn.jsdelivr.net/npm/sweetalert2@10.10.1/dist/sweetalert2.min.css\' /" +
                    ">\r\n    <script>\r\n        function HideLabelerror(msg) {\r\n            Swal.fire({" +
                    "\r\n                icon: \'error\',\r\n                text: msg,\r\n\r\n            })\r\n" +
                    "        };\r\n        function HideLabel(msg) {\r\n\r\n            Swal.fire({\r\n      " +
                    "          icon: \'success\',\r\n                text: msg,\r\n                timer: 2" +
                    "500,\r\n                showCancelButton: false,\r\n                showConfirmButto" +
                    "n: false\r\n            }).then(function () {\r\n                window.location.hre" +
                    "f = \"Admin/AdminDashboard.aspx\";\r\n            })\r\n        };\r\n    </script>\r\n</h" +
                    "ead>\r\n<body>\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        90,
                        2259,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=15.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.login_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.login_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n        <section class=\"login-block multiclr\">\r\n            <!-- Container-fl" +
                    "uid starts -->\r\n            <div class=\"container\">\r\n                <div class=" +
                    "\"row\">\r\n                   ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2381,
                        188,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                    <div class=\"col-md-12\">\r\n                        <!-- Authe" +
                    "ntication card start -->\r\n\r\n                        <div class=\"md-float-materia" +
                    "l form-material\">\r\n                           ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2656,
                        207,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                            <div class=""auth-box card"" style=""max-width: 385px;"">
                                <div class=""card-block"">
                                    <div class=""row m-b-20"">
                                        <div class=""col-md-12"">
                                            <h3 class=""text-center"">Sign In</h3>
                                        </div>
                                    </div>
                                    <br />
                                    <div class=""form-group form-primary"">
                                        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3022,
                        603,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtemail() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 86 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtemail = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 86 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ID = "txtemail";
            
            #line default
            #line hidden
            
            #line 86 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            
            #line default
            #line hidden
            
            #line 86 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Your Email Address");
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3625,
                        110,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3735,
                        42,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator3() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 87 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator3 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 87 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ID = "RequiredFieldValidator3";
            
            #line default
            #line hidden
            
            #line 87 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 87 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ErrorMessage = "Please Enter Your Email Address";
            
            #line default
            #line hidden
            
            #line 87 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ControlToValidate = "txtemail";
            
            #line default
            #line hidden
            
            #line 87 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 87 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 87 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3777,
                        303,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                        <span class=\"form-bar\"></span>\r\n       " +
                    "                             </div>\r\n                                    <div cl" +
                    "ass=\"form-group form-primary\">\r\n                                        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4080,
                        233,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtpassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 92 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtpassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 92 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ID = "txtpassword";
            
            #line default
            #line hidden
            
            #line 92 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            
            #line default
            #line hidden
            
            #line 92 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Password");
            
            #line default
            #line hidden
            
            #line 92 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4313,
                        123,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4436,
                        42,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator1() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 93 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 93 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ID = "RequiredFieldValidator1";
            
            #line default
            #line hidden
            
            #line 93 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 93 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ErrorMessage = "Please Enter Your Password";
            
            #line default
            #line hidden
            
            #line 93 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ControlToValidate = "txtpassword";
            
            #line default
            #line hidden
            
            #line 93 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 93 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 93 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4478,
                        301,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                        <span class=\"form-bar\"></span>\r\n       " +
                    "                             </div>\r\n                                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4779,
                        154,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblmsg() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 97 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblmsg = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 97 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ID = "lblmsg";
            
            #line default
            #line hidden
            
            #line 97 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.Text = "";
            
            #line default
            #line hidden
            
            #line 97 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 97 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4933,
                        90,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                    <div class=""row m-t-25 text-left"">
                                        <div class=""col-12"">
                                            <div class=""checkbox-fade fade-in-primary d-"">
                                                <label>
                                                    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5023,
                        337,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchkremember() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 102 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.chkremember = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 102 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ID = "chkremember";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5360,
                        48,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                                    <span class=""cr""><i class=""cr-icon icofont icofont-ui-check txt-primary""></i></span>
                                                    <span class=""text-inverse"">Remember me</span>
                                                </label>
                                            </div>
                                            <div class=""forgot-phone text-right f-right"">
                                                <a href=""#"" class=""text-right f-w-600"">Forgot Password?</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class=""row m-t-20"">
                                        <div class=""col-md-12"">
                                            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5408,
                        864,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnlogin() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnlogin = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ID = "btnlogin";
            
            #line default
            #line hidden
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.Text = "Sign in";
            
            #line default
            #line hidden
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.CssClass = "btn btn-primary btn-md btn-block waves-effect waves-light text-center m-b-2";
            
            #line default
            #line hidden
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnlogin_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6272,
                        194,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                            ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6466,
                        46,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                        </div>\r\n                               " +
                    "     </div>\r\n                                    <hr />\r\n                       " +
                    "             <div class=\"row\">\r\n                                        <div cla" +
                    "ss=\"col-md-6\">\r\n                                            <p class=\"text-inver" +
                    "se text-left m-b-0\">Thank you!</p>\r\n                                            " +
                    "<p class=\"text-inverse text-left\"><a href=\"#\" target=\"_blank\"><b class=\"f-w-600\"" +
                    ">Back to website</b></a></p>\r\n                                        </div>\r\n  " +
                    "                                      <div class=\"col-md-6\">\r\n                  " +
                    "                          <a href=\"#\" target=\"_blank\">\r\n                        " +
                    "                        <img src=\"img/ExcelEncLogo.png\" alt=\"logo\" width=\"130px\"" +
                    " /> </a>\r\n                                        </div>\r\n                      " +
                    "              </div>\r\n                                </div>\r\n                  " +
                    "          </div>\r\n                        </div>\r\n                        <!-- e" +
                    "nd of form -->\r\n                    </div>\r\n                    <!-- end of col-" +
                    "sm-12 -->\r\n                </div>\r\n                <!-- end of row -->\r\n        " +
                    "    </div>\r\n            <!-- end of container-fluid -->\r\n        </section>\r\n\r\n " +
                    "       <!-- Required Jquery -->\r\n        <script type=\"text/javascript\" src=\"..\\" +
                    "files\\bower_components\\jquery\\js\\jquery.min.js\"></script>\r\n        <script type=" +
                    "\"text/javascript\" src=\"..\\files\\bower_components\\bootstrap\\js\\bootstrap.min.js\">" +
                    "</script>\r\n\r\n    ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6559,
                        1538,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl2;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl4 = this.@__BuildControltxtemail();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl5 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl6;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl6 = this.@__BuildControlRequiredFieldValidator3();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl7 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl8;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl8 = this.@__BuildControltxtpassword();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl9 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl10;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl10 = this.@__BuildControlRequiredFieldValidator1();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl11 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl12;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl12 = this.@__BuildControllblmsg();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl13 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl14;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl14 = this.@__BuildControlchkremember();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl15 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl16;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl16 = this.@__BuildControlbtnlogin();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl17 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl18;
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl18 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 62 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2349,
                        5755,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8104,
                        20,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(login_aspx @__ctrl) {
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__ctrl3 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Login.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.login_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1370620683;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
