#pragma checksum "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "71F7D864091D1AFC52D0466EA716E359D6D959DE"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_SubCategoryMaster : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 104 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
    
    #line default
    #line hidden
    
    
    #line 136 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
    
    #line default
    #line hidden
    
    
    #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtSubCategoryName;
    
    #line default
    #line hidden
    
    
    #line 142 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
    
    #line default
    #line hidden
    
    
    #line 144 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender1;
    
    #line default
    #line hidden
    
    
    #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    protected global::System.Web.UI.WebControls.Label lblmsg;
    
    #line default
    #line hidden
    
    
    #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    protected global::System.Web.UI.WebControls.CheckBox chkIsactive;
    
    #line default
    #line hidden
    
    
    #line 165 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    protected global::System.Web.UI.WebControls.Button btnadd;
    
    #line default
    #line hidden
    
    
    #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    protected global::System.Web.UI.WebControls.Button btnreset;
    
    #line default
    #line hidden
    
    
    #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    protected global::System.Web.UI.UpdatePanel updatepnl;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    using AjaxControlToolkit;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_subcategorymaster_aspx : global::Admin_SubCategoryMaster, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.admin_subcategorymaster_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static System.Reflection.MethodInfo @__PageInspector_BeginRenderTracingMethod = global::ASP.admin_subcategorymaster_aspx.@__PageInspector_LoadHelper("BeginRenderTracing");
        
        private static System.Reflection.MethodInfo @__PageInspector_EndRenderTracingMethod = global::ASP.admin_subcategorymaster_aspx.@__PageInspector_LoadHelper("EndRenderTracing");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_subcategorymaster_aspx() {
            string[] dependencies;
            
            #line 912304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Admin/SubCategoryMaster.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_subcategorymaster_aspx.@__initialized == false)) {
                dependencies = new string[4];
                dependencies[0] = "~/Admin/SubCategoryMaster.aspx";
                dependencies[1] = "~/Admin/AdminMasterPage.master";
                dependencies[2] = "~/Admin/AdminMasterPage.master.cs";
                dependencies[3] = "~/Admin/SubCategoryMaster.aspx.cs";
                global::ASP.admin_subcategorymaster_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_subcategorymaster_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <style>\r\n        .dissablebtn {\r\n            cursor: not-allowed;\r\n        " +
                    "}\r\n    </style>\r\n    <style>\r\n        .spancls {\r\n            color: #5d5656 !im" +
                    "portant;\r\n            font-size: 13px !important;\r\n            font-weight: 600;" +
                    "\r\n            text-align: left;\r\n        }\r\n\r\n        .starcls {\r\n            co" +
                    "lor: red;\r\n            font-size: 18px;\r\n            font-weight: 700;\r\n        " +
                    "}\r\n\r\n        .card .card-header span {\r\n            color: #060606;\r\n           " +
                    " display: block;\r\n            font-size: 13px;\r\n            margin-top: 5px;\r\n  " +
                    "      }\r\n\r\n        .errspan {\r\n            float: right;\r\n            margin-rig" +
                    "ht: 6px;\r\n            margin-top: -25px;\r\n            position: relative;\r\n     " +
                    "       z-index: 2;\r\n            color: black;\r\n        }\r\n\r\n        .currentlbl " +
                    "{\r\n            text-align: center !important;\r\n        }\r\n\r\n        .completionL" +
                    "ist {\r\n            border: solid 1px Gray;\r\n            border-radius: 5px;\r\n   " +
                    "         margin: 0px;\r\n            padding: 3px;\r\n            height: 120px;\r\n  " +
                    "          overflow: auto;\r\n            background-color: #FFFFFF;\r\n        }\r\n\r\n" +
                    "        .listCategory {\r\n            color: #191919;\r\n        }\r\n\r\n        .Cate" +
                    "goryHighlighted {\r\n            background-color: #ADD6FF;\r\n        }\r\n\r\n        " +
                    ".reqcls {\r\n            color: red;\r\n            font-weight: 600;\r\n            f" +
                    "ont-size: 14px;\r\n        }\r\n\r\n        .aspNetDisabled {\r\n            cursor: not" +
                    "-allowed !important;\r\n        }\r\n\r\n        .rwotoppadding {\r\n            padding" +
                    "-top: 10px;\r\n        }\r\n    </style>\r\n    <script>\r\n        function HideLabel(m" +
                    "sg) {\r\n            Swal.fire({\r\n                icon: \'success\',\r\n              " +
                    "  text: msg,\r\n                timer: 3000,\r\n                showCancelButton: fa" +
                    "lse,\r\n                showConfirmButton: false\r\n            }).then(function () " +
                    "{\r\n                window.location.href = \"../Admin/AllCategoryList.aspx\";\r\n    " +
                    "        })\r\n        };\r\n    </script>\r\n    <style>\r\n        .row {\r\n            " +
                    "margin-top: 10px;\r\n        }\r\n    </style>\r\n    <script type=\'text/javascript\'>\r" +
                    "\n        function scrollToElement() {\r\n            var target = document.getElem" +
                    "entById(\"divdtls\").offsetTop;\r\n            window.scrollTo(0, target);\r\n        " +
                    "}\r\n    </script>\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        347,
                        2259,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=15.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.admin_subcategorymaster_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.admin_subcategorymaster_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        private void @__PageInspector_BeginRenderTracing(object[] parameters) {
            if ((global::ASP.admin_subcategorymaster_aspx.@__PageInspector_BeginRenderTracingMethod != null)) {
                global::ASP.admin_subcategorymaster_aspx.@__PageInspector_BeginRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        private void @__PageInspector_EndRenderTracing(object[] parameters) {
            if ((global::ASP.admin_subcategorymaster_aspx.@__PageInspector_EndRenderTracingMethod != null)) {
                global::ASP.admin_subcategorymaster_aspx.@__PageInspector_EndRenderTracingMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 5 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.ToolkitScriptManager @__BuildControlToolkitScriptManager1() {
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl;
            
            #line 104 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl = new global::AjaxControlToolkit.ToolkitScriptManager();
            
            #line default
            #line hidden
            this.ToolkitScriptManager1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 104 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ID = "ToolkitScriptManager1";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2715,
                        95,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            <div class=\"page-wrapper\">\r\n                <div class=\"page-body\">" +
                    "\r\n                    <div class=\"row\">\r\n                        <div class=\"col" +
                    "-md-7\">\r\n                        </div>\r\n                        <div class=\"col" +
                    "-md-5\">\r\n                            <div class=\"page-header-breadcrumb\">\r\n     " +
                    "                           <div style=\"float: right; margin: 3px; margin-bottom:" +
                    " 5px;\">\r\n                                    <span><a href=\"SubCategoryList.aspx" +
                    "\" style=\"font-size: 16px; border: 1px dashed gray; padding: 4px;\">&nbsp;Sub Cate" +
                    "gory List</a>&nbsp;&nbsp;\r\n                                    </span>\r\n        " +
                    "                        </div>\r\n                            </div>\r\n            " +
                    "            </div>\r\n                    </div>\r\n\r\n                    <div class" +
                    "=\"container py-3\">\r\n                        <div class=\"card\">\r\n                " +
                    "            <div class=\"card-header bg-primary text-uppercase text-white\">\r\n    " +
                    "                            <h5>Add Sub Category</h5>\r\n                         " +
                    "   </div>\r\n                            <div class=\"row\">\r\n                      " +
                    "          <div class=\"col-xl-12 col-md-12\">\r\n                                   " +
                    " <div class=\"card-header\">\r\n                                        <div class=\"" +
                    "row\">\r\n                                            <div class=\"col-md-12\">\r\n    " +
                    "                                            <div class=\"row\">\r\n\r\n               " +
                    "                                     <div class=\"col-md-2 spancls\">Category Name" +
                    "<i class=\"reqcls\">*&nbsp;</i> : </div>\r\n                                        " +
                    "            <div class=\"col-md-4\">\r\n                                            " +
                    "            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2890,
                        1693,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddlCategory() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 136 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.ddlCategory = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 136 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ID = "ddlCategory";
            
            #line default
            #line hidden
            
            #line 136 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4583,
                        93,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                                    </div>

                                                    <div class=""col-md-2 spancls"">SubCategory Name<i class=""reqcls"">*&nbsp;</i> : </div>
                                                    <div class=""col-md-4"">
                                                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4676,
                        334,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtSubCategoryName() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtSubCategoryName = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ID = "txtSubCategoryName";
            
            #line default
            #line hidden
            
            #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.TextChanged += new System.EventHandler(this.txtSubCategoryName_TextChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5010,
                        170,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5180,
                        58,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator1() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 142 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 142 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ID = "RequiredFieldValidator1";
            
            #line default
            #line hidden
            
            #line 142 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 142 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ErrorMessage = "Please Enter SubCategory Name";
            
            #line default
            #line hidden
            
            #line 142 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ControlToValidate = "txtSubCategoryName";
            
            #line default
            #line hidden
            
            #line 142 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 142 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 142 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5238,
                        327,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5565,
                        58,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.AutoCompleteExtender @__BuildControlAutoCompleteExtender1() {
            global::AjaxControlToolkit.AutoCompleteExtender @__ctrl;
            
            #line 144 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl = new global::AjaxControlToolkit.AutoCompleteExtender();
            
            #line default
            #line hidden
            this.AutoCompleteExtender1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 144 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ID = "AutoCompleteExtender1";
            
            #line default
            #line hidden
            
            #line 144 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.CompletionListCssClass = "completionList";
            
            #line default
            #line hidden
            
            #line 144 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.CompletionListHighlightedItemCssClass = "itemHighlighted";
            
            #line default
            #line hidden
            
            #line 144 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.CompletionListItemCssClass = "listItem";
            
            #line default
            #line hidden
            
            #line 144 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.CompletionInterval = 10;
            
            #line default
            #line hidden
            
            #line 144 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.MinimumPrefixLength = 1;
            
            #line default
            #line hidden
            
            #line 144 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ServiceMethod = "GetSubCategoryList";
            
            #line default
            #line hidden
            
            #line 144 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.TargetControlID = "txtSubCategoryName";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5623,
                        590,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6213,
                        58,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblmsg() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblmsg = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ID = "lblmsg";
            
            #line default
            #line hidden
            
            #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Text = "";
            
            #line default
            #line hidden
            
            #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6271,
                        90,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                    </div>\r\n                   " +
                    "                             </div>\r\n\r\n                                         " +
                    "       ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6361,
                        168,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                    <div class=\"col-md-2 spancl" +
                    "s\">Is Active: </div>\r\n                                                    <div c" +
                    "lass=\"col-md-4\">\r\n                                                        ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6561,
                        235,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.CheckBox @__BuildControlchkIsactive() {
            global::System.Web.UI.WebControls.CheckBox @__ctrl;
            
            #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.CheckBox();
            
            #line default
            #line hidden
            this.chkIsactive = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ID = "chkIsactive";
            
            #line default
            #line hidden
            
            #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Checked = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6796,
                        63,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                    </div>\r\n                   " +
                    "                             ");
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6859,
                        110,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            
            #line 153 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            
            #line 153 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "row");
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 153 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl1 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 153 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.CheckBox @__ctrl2;
            
            #line 153 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl2 = this.@__BuildControlchkIsactive();
            
            #line default
            #line hidden
            
            #line 153 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 153 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl3 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 153 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6529,
                        446,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"

                                                <div class=""row"">
                                                    <div class=""col-md-12"">
                                                        <div class=""row"">
                                                            <div class=""col-md-2""></div>
                                                            <div class=""col-md-2"">
                                                                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6975,
                        461,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnadd() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 165 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnadd = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 165 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ID = "btnadd";
            
            #line default
            #line hidden
            
            #line 165 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 165 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.CssClass = "btn btn-primary";
            
            #line default
            #line hidden
            
            #line 165 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 165 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Text = "Add SubCategory";
            
            #line default
            #line hidden
            
            #line 165 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnadd_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7436,
                        151,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                            </div>\r\n           " +
                    "                                                 <div class=\"col-md-2\">\r\n       " +
                    "                                                         <center> ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7587,
                        227,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnreset() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnreset = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ID = "btnreset";
            
            #line default
            #line hidden
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.CssClass = "btn btn-danger";
            
            #line default
            #line hidden
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Text = "Reset";
            
            #line default
            #line hidden
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnreset_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7814,
                        119,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"</center>
                                                            </div>
                                                            <div class=""col-md-6""></div>
                                                        </div>
                                                        <br />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7933,
                        745,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control3(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl2;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl2 = this.@__BuildControlddlCategory();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl4 = this.@__BuildControltxtSubCategoryName();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl5 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl6;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl6 = this.@__BuildControlRequiredFieldValidator1();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl7 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::AjaxControlToolkit.AutoCompleteExtender @__ctrl8;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl8 = this.@__BuildControlAutoCompleteExtender1();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl9 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl10;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl10 = this.@__BuildControllblmsg();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl11 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl12;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl12 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl13 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl14;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl14 = this.@__BuildControlbtnadd();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl15 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl16;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl16 = this.@__BuildControlbtnreset();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl17 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.UpdatePanel @__BuildControlupdatepnl() {
            global::System.Web.UI.UpdatePanel @__ctrl;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl = new global::System.Web.UI.UpdatePanel();
            
            #line default
            #line hidden
            this.updatepnl = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ContentTemplate = new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control3));
            
            #line default
            #line hidden
            
            #line 105 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.ID = "updatepnl";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2816,
                        5904,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl1;
            
            #line 103 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl1 = this.@__BuildControlToolkitScriptManager1();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 103 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.UpdatePanel @__ctrl2;
            
            #line 103 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl2 = this.@__BuildControlupdatepnl();
            
            #line default
            #line hidden
            
            #line 103 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__RenderContent2));
        }
        
        private void @__RenderContent2(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Admin/SubCategoryMaster.aspx",
                        2709,
                        6,
                        true});
            @__w.Write("\r\n    ");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[0].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Admin/SubCategoryMaster.aspx",
                        2810,
                        6,
                        true});
            @__w.Write("\r\n    ");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            parameterContainer.Controls[1].RenderControl(@__w);
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Admin/SubCategoryMaster.aspx",
                        8720,
                        122,
                        true});
            @__w.Write("\r\n    <script type=\"text/javascript\">\r\n        function DisableButton() {\r\n      " +
                    "      var btn = document.getElementById(\"");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Admin/SubCategoryMaster.aspx",
                        8842,
                        21,
                        false});
            
            #line 188 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
                                       @__w.Write(btnadd.ClientID );

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Admin/SubCategoryMaster.aspx",
                        8863,
                        85,
                        true});
            @__w.Write("\");\r\n            btn.value = \'Please wait...\';\r\n            document.getElementBy" +
                    "Id(\"");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Admin/SubCategoryMaster.aspx",
                        8948,
                        21,
                        false});
            
            #line 190 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
                             @__w.Write(btnadd.ClientID );

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Admin/SubCategoryMaster.aspx",
                        8969,
                        58,
                        true});
            @__w.Write("\").disabled = true;\r\n            document.getElementById(\"");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Admin/SubCategoryMaster.aspx",
                        9027,
                        21,
                        false});
            
            #line 191 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
                             @__w.Write(btnadd.ClientID );

            
            #line default
            #line hidden
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
            this.@__PageInspector_BeginRenderTracing(new object[] {
                        @__w,
                        "/Admin/SubCategoryMaster.aspx",
                        9048,
                        108,
                        true});
            @__w.Write("\").classList.add(\"dissablebtn\");\r\n        }\r\n        window.onbeforeunload = Disa" +
                    "bleButton;\r\n    </script>\r\n");
            this.@__PageInspector_EndRenderTracing(new object[] {
                        @__w});
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_subcategorymaster_aspx @__ctrl) {
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__ctrl.MasterPageFile = "~/Admin/AdminMasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 5 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 103 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\SubCategoryMaster.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_subcategorymaster_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1117387417;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
