//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.5.1")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_derjg5f4 {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_derjg5f4() {
        }
        
        static object Create_ASP_admin_purchasedashboard_aspx() {
            return new ASP.admin_purchasedashboard_aspx();
        }
        
        static object Create_ASP_admin_unitlist_aspx() {
            return new ASP.admin_unitlist_aspx();
        }
        
        static object Create_ASP_admin_departmentwiserpt_aspx() {
            return new ASP.admin_departmentwiserpt_aspx();
        }
        
        static object Create_ASP_admin_partyledgerreport_aspx() {
            return new ASP.admin_partyledgerreport_aspx();
        }
        
        static object Create_ASP_admin_payment_aspx() {
            return new ASP.admin_payment_aspx();
        }
        
        static object Create_ASP_admin_welding_aspx() {
            return new ASP.admin_welding_aspx();
        }
        
        static object Create_ASP_admin_quotationcat2_aspx() {
            return new ASP.admin_quotationcat2_aspx();
        }
    }
}
