//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.5.1")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_wujsu4jx {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_wujsu4jx() {
        }
        
        static object Create_ASP_admin_paymentmodule_aspx() {
            return new ASP.admin_paymentmodule_aspx();
        }
        
        static object Create_ASP_admin_purchasebilllist_aspx() {
            return new ASP.admin_purchasebilllist_aspx();
        }
        
        static object Create_ASP_admin_deliverychallanlist_aspx() {
            return new ASP.admin_deliverychallanlist_aspx();
        }
        
        static object Create_ASP_admin_deliverychallan_aspx() {
            return new ASP.admin_deliverychallan_aspx();
        }
    }
}
