#pragma checksum "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "07834F7436873DEAAB8B9F2269AB74F0BC34F05B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_userprofile : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 92 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
    
    #line default
    #line hidden
    
    
    #line 132 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtname;
    
    #line default
    #line hidden
    
    
    #line 133 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
    
    #line default
    #line hidden
    
    
    #line 138 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtemail;
    
    #line default
    #line hidden
    
    
    #line 139 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
    
    #line default
    #line hidden
    
    
    #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.Label lblmsg;
    
    #line default
    #line hidden
    
    
    #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtemailpsw;
    
    #line default
    #line hidden
    
    
    #line 150 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
    
    #line default
    #line hidden
    
    
    #line 155 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtpanelpsw;
    
    #line default
    #line hidden
    
    
    #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
    
    #line default
    #line hidden
    
    
    #line 193 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtmobile;
    
    #line default
    #line hidden
    
    
    #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.DropDownList ddldept;
    
    #line default
    #line hidden
    
    
    #line 205 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
    
    #line default
    #line hidden
    
    
    #line 216 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.Button btnadd;
    
    #line default
    #line hidden
    
    
    #line 219 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    protected global::System.Web.UI.WebControls.Button btnreset;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    using AjaxControlToolkit;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_userprofile_aspx : global::Admin_userprofile, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.admin_userprofile_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_userprofile_aspx() {
            string[] dependencies;
            
            #line 912304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Admin/userprofile.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_userprofile_aspx.@__initialized == false)) {
                global::ASP.admin_userprofile_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/Admin/userprofile.aspx";
                dependencies[1] = "~/Admin/AdminMasterPage.master";
                dependencies[2] = "~/Admin/AdminMasterPage.master.cs";
                dependencies[3] = "~/Admin/userprofile.aspx.cs";
                global::ASP.admin_userprofile_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_userprofile_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <style>\r\n        .spancls {\r\n            color: #5d5656 !important;\r\n      " +
                    "      font-size: 13px !important;\r\n            font-weight: 600;\r\n            te" +
                    "xt-align: left;\r\n        }\r\n\r\n        .starcls {\r\n            color: red;\r\n     " +
                    "       font-size: 18px;\r\n            font-weight: 700;\r\n        }\r\n\r\n        .ca" +
                    "rd .card-header span {\r\n            color: #060606;\r\n            display: block;" +
                    "\r\n            font-size: 13px;\r\n            margin-top: 5px;\r\n        }\r\n    </s" +
                    "tyle>\r\n\r\n    <style>\r\n        .modelprofile1 {\r\n            background-color: rg" +
                    "ba(0, 0, 0, 0.54);\r\n            display: block;\r\n            position: fixed;\r\n " +
                    "           z-index: 1;\r\n            left: 0;\r\n            /*top: 10px;*/\r\n      " +
                    "      height: 100%;\r\n            overflow: auto;\r\n            width: 100%;\r\n    " +
                    "        margin-bottom: 25px;\r\n        }\r\n\r\n        .profilemodel2 {\r\n           " +
                    " background-color: #fefefe;\r\n            margin-top: 45px;\r\n            padding:" +
                    " 17px 5px 18px 22px;\r\n            /*border: 2px solid #c5bebe;*/\r\n            wi" +
                    "dth: 100%;\r\n            top: 40px;\r\n            color: #000;\r\n            border" +
                    "-radius: 5px;\r\n        }\r\n\r\n        .lblpopup {\r\n            text-align: left;\r\n" +
                    "        }\r\n\r\n        .wp-block-separator:not(.is-style-wide):not(.is-style-dots)" +
                    "::before, hr:not(.is-style-wide):not(.is-style-dots)::before {\r\n            cont" +
                    "ent: \'\';\r\n            display: block;\r\n            height: 1px;\r\n            wid" +
                    "th: 100%;\r\n            background: #cccccc;\r\n        }\r\n\r\n        .btnclose {\r\n " +
                    "           float: right;\r\n            font-size: 15px !important;\r\n            /" +
                    "*font-weight: 600;*/\r\n            color: #ff5a5f !important;\r\n            border" +
                    ": 0px groove !important;\r\n            background-color: none !important;\r\n      " +
                    "      margin-right: 10px !important;\r\n            cursor: pointer;\r\n        }\r\n\r" +
                    "\n        hr {\r\n            margin-top: 5px !important;\r\n            margin-botto" +
                    "m: 15px !important;\r\n            border: 1px solid #eae6e6 !important;\r\n        " +
                    "    width: 100%;\r\n        }\r\n        .reqcls{\r\n            color:red;\r\n         " +
                    "   font-weight:600;\r\n            font-size:14px;\r\n        }\r\n    </style>\r\n\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        337,
                        2158,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=15.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.admin_userprofile_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.admin_userprofile_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 6 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2596,
                        6,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.ToolkitScriptManager @__BuildControlToolkitScriptManager1() {
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl;
            
            #line 92 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::AjaxControlToolkit.ToolkitScriptManager();
            
            #line default
            #line hidden
            this.ToolkitScriptManager1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 92 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "ToolkitScriptManager1";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2602,
                        95,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
    <div class=""page-wrapper"">
        <div class=""page-body"">
            <div class=""row"">
                <div class=""col-md-7"">
                    <div class=""page-header-breadcrumb"">
                        <div style=""float: left; font-size: 15px;"">
                            <span><i class=""feather icon-home""></i>&nbsp;Profile</span>
                        </div>
                    </div>
                </div>


                <div class=""col-md-5"">
                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2697,
                        502,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                </div>
            </div>

            <div class=""container py-3"">
                <div class=""card"">
                    <div class=""card-header bg-primary text-uppercase text-white"">
                        <h5><i class=""fa fa-user-plus""></i>My Profile</h5>
                    </div>

                    <div class=""row"">
                        <div class=""col-xl-12 col-md-12"">
                            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3729,
                        442,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                <div class=""card-header"">
                                    <div class=""row"">
                                        <div class=""col-md-12"">
                                            <br />
                                            <div class=""row"">
                                                <div class=""col-md-2 spancls"">Name<i class=""reqcls"">*&nbsp;</i> : </div>
                                                <div class=""col-md-4"">
                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4197,
                        542,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtname() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 132 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtname = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 132 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "txtname";
            
            #line default
            #line hidden
            
            #line 132 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 132 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4739,
                        92,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4831,
                        54,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator1() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 133 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 133 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "RequiredFieldValidator1";
            
            #line default
            #line hidden
            
            #line 133 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 133 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ErrorMessage = "Please Enter Name";
            
            #line default
            #line hidden
            
            #line 133 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ControlToValidate = "txtname";
            
            #line default
            #line hidden
            
            #line 133 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 133 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 133 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4885,
                        300,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                                </div>
                                                <div class=""col-md-2 spancls"">Email<i class=""reqcls"">*&nbsp;</i> : </div>
                                                <div class=""col-md-4"">
                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5185,
                        305,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtemail() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 138 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtemail = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 138 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "txtemail";
            
            #line default
            #line hidden
            
            #line 138 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 138 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 138 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 138 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.TextChanged += new System.EventHandler(this.txtemail_TextChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5490,
                        150,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5640,
                        54,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator2() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 139 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator2 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 139 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "RequiredFieldValidator2";
            
            #line default
            #line hidden
            
            #line 139 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 139 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ErrorMessage = "Please Enter Email";
            
            #line default
            #line hidden
            
            #line 139 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ControlToValidate = "txtemail";
            
            #line default
            #line hidden
            
            #line 139 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 139 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 139 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5694,
                        302,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5996,
                        54,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblmsg() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblmsg = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "lblmsg";
            
            #line default
            #line hidden
            
            #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Text = "";
            
            #line default
            #line hidden
            
            #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 141 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6050,
                        90,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                                </div>
                                            </div>
                                            <br />

                                            <div class=""row"">
                                                <div class=""col-md-2 spancls"">Email Password<i class=""reqcls"">*&nbsp;</i> : </div>
                                                <div class=""col-md-4"">
                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6140,
                        483,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtemailpsw() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtemailpsw = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "txtemailpsw";
            
            #line default
            #line hidden
            
            #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            
            #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 149 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6623,
                        116,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6739,
                        54,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator3() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 150 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator3 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 150 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "RequiredFieldValidator3";
            
            #line default
            #line hidden
            
            #line 150 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 150 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ErrorMessage = "Please Enter Email Password";
            
            #line default
            #line hidden
            
            #line 150 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ControlToValidate = "txtemailpsw";
            
            #line default
            #line hidden
            
            #line 150 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 150 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 150 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6793,
                        314,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                                </div>
                                                <div class=""col-md-2 spancls"">Panel Password<i class=""reqcls"">*&nbsp;</i> : </div>
                                                <div class=""col-md-4"">
                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7107,
                        314,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtpanelpsw() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 155 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtpanelpsw = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 155 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "txtpanelpsw";
            
            #line default
            #line hidden
            
            #line 155 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            
            #line 155 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 155 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7421,
                        116,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7537,
                        54,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator4() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator4 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "RequiredFieldValidator4";
            
            #line default
            #line hidden
            
            #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ErrorMessage = "Please Enter Panel Password";
            
            #line default
            #line hidden
            
            #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ControlToValidate = "txtpanelpsw";
            
            #line default
            #line hidden
            
            #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 156 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7591,
                        314,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                </div>\r\n                       " +
                    "                     </div>\r\n                                            <div cl" +
                    "ass=\"row\">\r\n                                                <div class=\"col-md-2" +
                    "\"></div>\r\n                                                <div class=\"col-md-4\">" +
                    "\r\n                                                    &nbsp;<input type=\"checkbo" +
                    "x\" onclick=\"ShowPsw1()\">&nbsp;&nbsp;<p style=\"font-size:12px;display: inline;\">S" +
                    "how Password</p>\r\n                                                </div>\r\n      " +
                    "                                          <div class=\"col-md-2\"></div>\r\n        " +
                    "                                        <div class=\"col-md-4\">\r\n                " +
                    "                                    &nbsp;<input type=\"checkbox\" onclick=\"ShowPs" +
                    "w2()\">&nbsp;&nbsp;<p style=\"font-size:12px;display: inline;\">Show Password</p>\r\n" +
                    "                                                </div>\r\n                        " +
                    "                    </div>\r\n                                            <br />\r\n" +
                    "                                            <script>\r\n                          " +
                    "                      function ShowPsw1() {\r\n                                   " +
                    "                 var x = document.getElementById(\"ContentPlaceHolder1_txtemailps" +
                    "w\");\r\n                                                    if (x.type === \"passwo" +
                    "rd\") {\r\n                                                        x.type = \"text\";" +
                    "\r\n                                                    } else {\r\n                " +
                    "                                        x.type = \"password\";\r\n                  " +
                    "                                  }\r\n                                           " +
                    "     }\r\n\r\n                                                function ShowPsw2() {\r" +
                    "\n                                                    var x = document.getElement" +
                    "ById(\"ContentPlaceHolder1_txtpanelpsw\");\r\n                                      " +
                    "              if (x.type === \"password\") {\r\n                                    " +
                    "                    x.type = \"text\";\r\n                                          " +
                    "          } else {\r\n                                                        x.ty" +
                    "pe = \"password\";\r\n                                                    }\r\n       " +
                    "                                         }\r\n                                    " +
                    "        </script>\r\n                                            <div class=\"row\">" +
                    "\r\n                                                <div class=\"col-md-2 spancls\">" +
                    "Mobile : </div>\r\n                                                <div class=\"col" +
                    "-md-4\">\r\n                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7905,
                        2622,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtmobile() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 193 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtmobile = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 193 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "txtmobile";
            
            #line default
            #line hidden
            
            #line 193 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 193 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10527,
                        94,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                                </div>
                                                <div class=""col-md-2 spancls"">Department<i class=""reqcls"">*&nbsp;</i> : </div>
                                                <div class=""col-md-4"">
                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10621,
                        310,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control18() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 198 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 198 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Text = "Select";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control19() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 199 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 199 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Text = "Admin";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control20() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 200 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 200 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Text = "Sales";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control21() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 201 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 201 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Text = "BDE";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control22() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 202 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 202 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Text = "Designer";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control23() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            
            #line 203 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            
            #line default
            #line hidden
            
            #line 203 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Text = "Developer";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control17(System.Web.UI.WebControls.ListItemCollection @__ctrl) {
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl1 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl2 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl3 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl4;
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl4 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl5;
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl5 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ListItem @__ctrl6;
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl6 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlddldept() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            
            #line default
            #line hidden
            this.ddldept = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "ddldept";
            
            #line default
            #line hidden
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Enabled = false;
            
            #line default
            #line hidden
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 197 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            this.@__BuildControl__control17(@__ctrl.Items);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10931,
                        730,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control24() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11661,
                        54,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator5() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 205 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator5 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 205 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "RequiredFieldValidator5";
            
            #line default
            #line hidden
            
            #line 205 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 205 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ErrorMessage = "Please Select Department";
            
            #line default
            #line hidden
            
            #line 205 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ControlToValidate = "ddldept";
            
            #line default
            #line hidden
            
            #line 205 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.InitialValue = "Select";
            
            #line default
            #line hidden
            
            #line 205 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 205 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 205 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11715,
                        329,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control25() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                                </div>
                                            </div>
                                            <br />

                                       
                                            <br />
                                            <div class=""row"">
                                                <div class=""col-md-2""></div>
                                                <div class=""col-md-2"">
                                                    <center> ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12044,
                        531,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnadd() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 216 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnadd = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 216 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "btnadd";
            
            #line default
            #line hidden
            
            #line 216 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 216 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.CssClass = "btn btn-success";
            
            #line default
            #line hidden
            
            #line 216 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 216 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Text = "Add User";
            
            #line default
            #line hidden
            
            #line 216 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnadd_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12575,
                        143,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control26() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("</center>\r\n                                                </div>\r\n              " +
                    "                                  <div class=\"col-md-2\">\r\n                      " +
                    "                              <center> ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12718,
                        200,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnreset() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 219 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnreset = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 219 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.ID = "btnreset";
            
            #line default
            #line hidden
            
            #line 219 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.CssClass = "btn btn-danger";
            
            #line default
            #line hidden
            
            #line 219 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 219 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Text = "Reset";
            
            #line default
            #line hidden
            
            #line 219 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnreset_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12918,
                        119,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control27() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"</center>
                                                </div>
                                                <div class=""col-md-6""></div>

                                            </div>
                                            <br />

                                        </div>
                                    </div>
                                </div>
                           ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13037,
                        412,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control28() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                        </div>\r\n                    </div>\r\n\r\n                <" +
                    "/div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n\r\n\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13464,
                        142,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl2;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl2 = this.@__BuildControlToolkitScriptManager1();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl3 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl4;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl4 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl5 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl6;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl6 = this.@__BuildControltxtname();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl7 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl8;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl8 = this.@__BuildControlRequiredFieldValidator1();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl9 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl10;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl10 = this.@__BuildControltxtemail();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl11 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl12;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl12 = this.@__BuildControlRequiredFieldValidator2();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl13 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl14;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl14 = this.@__BuildControllblmsg();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl15 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl16;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl16 = this.@__BuildControltxtemailpsw();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl17 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl18;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl18 = this.@__BuildControlRequiredFieldValidator3();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl19;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl19 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl20;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl20 = this.@__BuildControltxtpanelpsw();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl20);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl21;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl21 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl21);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl22;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl22 = this.@__BuildControlRequiredFieldValidator4();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl22);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl23;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl23 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl23);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl24;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl24 = this.@__BuildControltxtmobile();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl24);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl25;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl25 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl25);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.DropDownList @__ctrl26;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl26 = this.@__BuildControlddldept();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl26);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl27;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl27 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl27);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl28;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl28 = this.@__BuildControlRequiredFieldValidator5();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl28);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl29;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl29 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl29);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl30;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl30 = this.@__BuildControlbtnadd();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl30);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl31;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl31 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl31);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl32;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl32 = this.@__BuildControlbtnreset();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl32);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl33;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl33 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl33);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl34;
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl34 = this.@__BuildControl__control28();
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(@__ctrl34);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_userprofile_aspx @__ctrl) {
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__ctrl.MasterPageFile = "~/Admin/AdminMasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 6 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 91 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\userprofile.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.admin_userprofile_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_userprofile_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1349023136;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
