#pragma checksum "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "260B8555EFF2B0A5F2A30DD93B66892F84538C94"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_CategoryList : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 233 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
    
    #line default
    #line hidden
    
    
    #line 267 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtcnamefilter;
    
    #line default
    #line hidden
    
    
    #line 268 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender1;
    
    #line default
    #line hidden
    
    
    #line 275 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    protected global::System.Web.UI.WebControls.Button btnresetfilter;
    
    #line default
    #line hidden
    
    
    #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    protected global::System.Web.UI.WebControls.GridView GvCategory;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    using AjaxControlToolkit;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_categorylist_aspx : global::Admin_CategoryList, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.admin_categorylist_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_categorylist_aspx() {
            string[] dependencies;
            
            #line 912304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Admin/CategoryList.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_categorylist_aspx.@__initialized == false)) {
                dependencies = new string[4];
                dependencies[0] = "~/Admin/CategoryList.aspx";
                dependencies[1] = "~/Admin/AdminMasterPage.master";
                dependencies[2] = "~/Admin/AdminMasterPage.master.cs";
                dependencies[3] = "~/Admin/CategoryList.aspx.cs";
                global::ASP.admin_categorylist_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_categorylist_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <style>\r\n        .spancls {\r\n            color: #5d5656 !important;\r\n      " +
                    "      font-size: 13px !important;\r\n            font-weight: 600;\r\n            te" +
                    "xt-align: left;\r\n        }\r\n\r\n        .starcls {\r\n            color: red;\r\n     " +
                    "       font-size: 18px;\r\n            font-weight: 700;\r\n        }\r\n\r\n        .so" +
                    "rtable-handler {\r\n            touch-action: none;\r\n        }\r\n\r\n        .card .c" +
                    "ard-header span {\r\n            color: #060606;\r\n            display: block;\r\n   " +
                    "         font-size: 13px;\r\n            margin-top: 5px;\r\n        }\r\n\r\n        .b" +
                    "tn {\r\n            padding: 5px 5px !important;\r\n        }\r\n    </style>\r\n\r\n    <" +
                    "style>\r\n        .modelprofile1 {\r\n            background-color: rgba(0, 0, 0, 0." +
                    "54);\r\n            display: block;\r\n            position: fixed;\r\n            z-i" +
                    "ndex: 1;\r\n            left: 0;\r\n            /*top: 10px;*/\r\n            height: " +
                    "100%;\r\n            overflow: auto;\r\n            width: 100%;\r\n            margin" +
                    "-bottom: 25px;\r\n        }\r\n\r\n        .profilemodel2 {\r\n            background-co" +
                    "lor: #fefefe;\r\n            margin-top: 25px;\r\n            /*padding: 17px 5px 18" +
                    "px 22px;*/\r\n            padding: 0px 0px 15px 0px;\r\n            width: 100%;\r\n  " +
                    "          top: 40px;\r\n            color: #000;\r\n            border-radius: 5px;\r" +
                    "\n        }\r\n\r\n        .lblpopup {\r\n            text-align: left;\r\n        }\r\n\r\n " +
                    "       .wp-block-separator:not(.is-style-wide):not(.is-style-dots)::before, hr:n" +
                    "ot(.is-style-wide):not(.is-style-dots)::before {\r\n            content: \'\';\r\n    " +
                    "        display: block;\r\n            height: 1px;\r\n            width: 100%;\r\n   " +
                    "         background: #cccccc;\r\n        }\r\n\r\n        .btnclose {\r\n            bac" +
                    "kground-color: #ef1e24;\r\n            float: right;\r\n            font-size: 18px " +
                    "!important;\r\n            /* font-weight: 600; */\r\n            color: #f7f6f6 !im" +
                    "portant;\r\n            border: 0px groove !important;\r\n            background-col" +
                    "or: none !important;\r\n            /*margin-right: 10px !important;*/\r\n          " +
                    "  cursor: pointer;\r\n            font-weight: 600;\r\n            border-radius: 4p" +
                    "x;\r\n            padding: 4px;\r\n        }\r\n\r\n        /*hr {\r\n            margin-t" +
                    "op: 5px !important;\r\n            margin-bottom: 15px !important;\r\n            bo" +
                    "rder: 1px solid #eae6e6 !important;\r\n            width: 100%;\r\n        }*/\r\n    " +
                    "    hr.new1 {\r\n            border-top: 1px dashed green !important;\r\n           " +
                    " border: 0;\r\n            margin-top: 5px !important;\r\n            margin-bottom:" +
                    " 5px !important;\r\n            width: 100%;\r\n        }\r\n\r\n        .errspan {\r\n   " +
                    "         float: right;\r\n            margin-right: 6px;\r\n            margin-top: " +
                    "-25px;\r\n            position: relative;\r\n            z-index: 2;\r\n            co" +
                    "lor: black;\r\n        }\r\n\r\n        .currentlbl {\r\n            text-align: center " +
                    "!important;\r\n        }\r\n\r\n        .completionList {\r\n            border: solid 1" +
                    "px Gray;\r\n            border-radius: 5px;\r\n            margin: 0px;\r\n           " +
                    " padding: 3px;\r\n            height: 120px;\r\n            overflow: auto;\r\n       " +
                    "     background-color: #FFFFFF;\r\n        }\r\n\r\n        .listItem {\r\n            c" +
                    "olor: #191919;\r\n        }\r\n\r\n        .itemHighlighted {\r\n            background-" +
                    "color: #ADD6FF;\r\n        }\r\n\r\n        .headingcls {\r\n            background-colo" +
                    "r: #01a9ac;\r\n            color: #fff;\r\n            padding: 15px;\r\n            b" +
                    "order-radius: 5px 5px 0px 0px;\r\n        }\r\n\r\n\r\n\r\n\r\n        @media (min-width: 12" +
                    "00px) {\r\n            .container {\r\n                max-width: 100% !important;\r\n" +
                    "            }\r\n        }\r\n    </style>\r\n\r\n    <style type=\"text/css\">\r\n        ." +
                    "divgrid {\r\n            height: 200px;\r\n            width: 370px;\r\n        }\r\n\r\n " +
                    "           .divgrid table {\r\n                width: 350px;\r\n            }\r\n\r\n   " +
                    "             .divgrid table th {\r\n                    background-color: Green;\r\n" +
                    "                    color: #fff;\r\n                }\r\n    </style>\r\n\r\n\r\n    <scri" +
                    "pt src=\"../JS/jquery.min.js\"></script>\r\n    <script language=\"javascript\" type=\"" +
                    "text/javascript\">\r\n\r\n        function MakeStaticHeader(gridId, height, width, he" +
                    "aderHeight, isFooter) {\r\n\r\n            $(\'#btnshowhide\').hide();\r\n\r\n            " +
                    "var tbl = document.getElementById(gridId);\r\n            if (tbl) {\r\n            " +
                    "    var DivHR = document.getElementById(\'DivHeaderRow\');\r\n                var Di" +
                    "vMC = document.getElementById(\'DivMainContent\');\r\n                var DivFR = do" +
                    "cument.getElementById(\'DivFooterRow\');\r\n\r\n                var wid = 100;\r\n\r\n    " +
                    "            //*** Set divheaderRow Properties ****\r\n                DivHR.style." +
                    "height = headerHeight + \'px\';\r\n                DivHR.style.width = wid + \"%\";\r\n " +
                    "               DivHR.style.position = \'relative\';\r\n                DivHR.style.t" +
                    "op = \'0px\';\r\n                DivHR.style.zIndex = \'10\';\r\n                DivHR.s" +
                    "tyle.verticalAlign = \'top\';\r\n\r\n                //*** Set divMainContent Properti" +
                    "es ****\r\n                DivMC.style.width = wid + \"%\";\r\n                DivMC.s" +
                    "tyle.height = height + \'px\';\r\n                DivMC.style.position = \'relative\';" +
                    "\r\n                DivMC.style.top = -headerHeight + \'px\';\r\n                DivMC" +
                    ".style.zIndex = \'1\';\r\n\r\n                //*** Set divFooterRow Properties ****\r\n" +
                    "                DivFR.style.width = wid + \"%\";\r\n                DivFR.style.posi" +
                    "tion = \'relative\';\r\n                DivFR.style.top = -headerHeight + \'%\';\r\n    " +
                    "            DivFR.style.verticalAlign = \'top\';\r\n                DivFR.style.padd" +
                    "ingtop = \'2px\';\r\n\r\n                //if (isFooter) {\r\n                //    var " +
                    "tblfr = tbl.cloneNode(true);\r\n                //    tblfr.removeChild(tblfr.getE" +
                    "lementsByTagName(\'tbody\')[0]);\r\n                //    var tblBody = document.cre" +
                    "ateElement(\'tbody\');\r\n                //    tblfr.style.width = \'100%\';\r\n       " +
                    "         //    tblfr.cellSpacing = \"0\";\r\n                //    tblfr.border = \"0" +
                    "px\";\r\n                //    tblfr.rules = \"none\";\r\n                //    //*****" +
                    "In the case of Footer Row *******\r\n                //    tblBody.appendChild(tbl" +
                    ".rows[tbl.rows.length - 1]);\r\n                //    tblfr.appendChild(tblBody);\r" +
                    "\n                //    DivFR.appendChild(tblfr);\r\n                //}\r\n         " +
                    "       //****Copy Header in divHeaderRow****\r\n\r\n\r\n                DivHR.appendCh" +
                    "ild(tbl.cloneNode(true));\r\n\r\n            }\r\n        }\r\n\r\n        function OnScro" +
                    "llDiv(Scrollablediv) {\r\n            document.getElementById(\'DivHeaderRow\').scro" +
                    "llLeft = Scrollablediv.scrollLeft;\r\n            document.getElementById(\'DivFoot" +
                    "erRow\').scrollLeft = Scrollablediv.scrollLeft;\r\n        }\r\n    </script>\r\n\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        337,
                        6557,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=15.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.admin_categorylist_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.admin_categorylist_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 5 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 5 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6995,
                        6,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.ToolkitScriptManager @__BuildControlToolkitScriptManager1() {
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl;
            
            #line 233 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::AjaxControlToolkit.ToolkitScriptManager();
            
            #line default
            #line hidden
            this.ToolkitScriptManager1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 233 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ID = "ToolkitScriptManager1";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7001,
                        95,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"

    <div class=""page-wrapper"">
        <div class=""page-body"">

            <div class=""row"">
                <div class=""col-md-7"">
                </div>
                <div class=""col-md-5"">
                    <div class=""page-header-breadcrumb"">
                        <div style=""float: right; margin: 3px; margin-bottom: 5px;"">
                            <span><a href=""CategoryMaster.aspx"" style=""font-size: 16px; border: 1px dashed gray; padding: 4px;"">&nbsp;Add Category</a>&nbsp;&nbsp;
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class=""container py-3"">
                <div class=""card"">
                    <div class=""card-header bg-primary text-uppercase text-white"">
                        <div class=""row"">
                            <div class=""col-md-4"">
                                <h5>Category List</h5>
                            </div>
                        </div>
                    </div>
                    <div class=""row"">
                        <div class=""col-xl-12 col-md-12"">
                            <div class=""card"">
                                <div class=""card-header"">

                                    <div class=""row"">
                                        <div class=""col-xl-3 col-md-3"">
                                            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7096,
                        1445,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtcnamefilter() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 267 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtcnamefilter = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 267 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ID = "txtcnamefilter";
            
            #line default
            #line hidden
            
            #line 267 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 267 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("placeholder", "Category name");
            
            #line default
            #line hidden
            
            #line 267 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 267 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 267 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.TextChanged += new System.EventHandler(this.txtcnamefilter_TextChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8541,
                        190,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8731,
                        46,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.AutoCompleteExtender @__BuildControlAutoCompleteExtender1() {
            global::AjaxControlToolkit.AutoCompleteExtender @__ctrl;
            
            #line 268 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::AjaxControlToolkit.AutoCompleteExtender();
            
            #line default
            #line hidden
            this.AutoCompleteExtender1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 268 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ID = "AutoCompleteExtender1";
            
            #line default
            #line hidden
            
            #line 268 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.CompletionListCssClass = "completionList";
            
            #line default
            #line hidden
            
            #line 268 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.CompletionListHighlightedItemCssClass = "itemHighlighted";
            
            #line default
            #line hidden
            
            #line 268 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.CompletionListItemCssClass = "listItem";
            
            #line default
            #line hidden
            
            #line 268 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.CompletionInterval = 10;
            
            #line default
            #line hidden
            
            #line 268 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.MinimumPrefixLength = 1;
            
            #line default
            #line hidden
            
            #line 268 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ServiceMethod = "GetCategoryList";
            
            #line default
            #line hidden
            
            #line 268 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.TargetControlID = "txtcnamefilter";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8777,
                        535,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                        </div>\r\n                               " +
                    "         <div class=\"col-xl-1 col-md-1\">\r\n                                      " +
                    "      ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9312,
                        167,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnresetfilter() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 275 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnresetfilter = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 275 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ID = "btnresetfilter";
            
            #line default
            #line hidden
            
            #line 275 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.CssClass = "btn btn-danger";
            
            #line default
            #line hidden
            
            #line 275 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.Text = "Reset";
            
            #line default
            #line hidden
            
            #line 275 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "padding: 8px;");
            
            #line default
            #line hidden
            
            #line 275 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnresetfilter_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9479,
                        141,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                        </div>
                                    </div>
                                    <div class=""col-md-12"" style=""padding: 0px; margin-top: 10px;"">
                                        <div id=""DivRoot"" align=""left"">
                                            <div style=""overflow: hidden;"" id=""DivHeaderRow"">
                                            </div>
                                            <div style=""overflow: scroll;"" class=""dt-responsive table-responsive"" onscroll=""OnScrollDiv(this)"" id=""DivMainContent"">
                                                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9620,
                        628,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10881,
                        66,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control12() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 289 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 289 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ID = "lblsno";
            
            #line default
            #line hidden
            
            #line 289 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control12);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10947,
                        90,
                        false});
            return @__ctrl;
        }
        
        public void @__DataBinding__control12(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 289 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            
            #line default
            #line hidden
            
            #line 289 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 289 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Container.DataItemIndex+1 , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11037,
                        62,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control10(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 287 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl1 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 287 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl2;
            
            #line 287 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl2 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 287 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 287 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl3 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 287 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control9() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 287 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 287 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control10), null);
            
            #line default
            #line hidden
            
            #line 287 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.HeaderText = "SNo.";
            
            #line default
            #line hidden
            
            #line 287 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(50D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 287 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11402,
                        66,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control17() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 294 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 294 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ID = "lblCategory";
            
            #line default
            #line hidden
            
            #line 294 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control17);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11468,
                        86,
                        false});
            return @__ctrl;
        }
        
        public void @__DataBinding__control17(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 294 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            
            #line default
            #line hidden
            
            #line 294 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 294 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("Category") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11554,
                        62,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control15(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 292 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl1 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 292 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl2;
            
            #line 292 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl2 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 292 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 292 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl3 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 292 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control14() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 292 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 292 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control15), null);
            
            #line default
            #line hidden
            
            #line 292 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.HeaderText = "Category";
            
            #line default
            #line hidden
            
            #line 292 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control21() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        11978,
                        66,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControl__control22() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 300 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 300 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ID = "lblCreatedBy";
            
            #line default
            #line hidden
            
            #line 300 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control22);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12044,
                        88,
                        false});
            return @__ctrl;
        }
        
        public void @__DataBinding__control22(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Label dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 300 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Label)(sender));
            
            #line default
            #line hidden
            
            #line 300 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 300 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString( Eval("CreatedBy") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control23() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12132,
                        62,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control20(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 298 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl1 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 298 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl2;
            
            #line 298 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl2 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 298 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 298 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl3 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 298 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control19() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 298 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 298 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control20), null);
            
            #line default
            #line hidden
            
            #line 298 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.HeaderText = "CreatedBy";
            
            #line default
            #line hidden
            
            #line 298 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control26() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12497,
                        66,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControl__control27() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 306 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 306 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ID = "Button4";
            
            #line default
            #line hidden
            
            #line 306 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.CssClass = "btn";
            
            #line default
            #line hidden
            
            #line 306 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.Text = "Edit";
            
            #line default
            #line hidden
            
            #line 306 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "background-color: #09989a !important; color: #fff;");
            
            #line default
            #line hidden
            
            #line 306 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.CommandName = "RowEdit";
            
            #line default
            #line hidden
            
            #line 306 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control27);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12563,
                        186,
                        false});
            return @__ctrl;
        }
        
        public void @__DataBinding__control27(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.Button dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 306 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.Button)(sender));
            
            #line default
            #line hidden
            
            #line 306 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 306 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            dataBindingExpressionBuilderTarget.CommandArgument = global::System.Convert.ToString( Eval("Id") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control28() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        12749,
                        62,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control25(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl1 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl2;
            
            #line 304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl2 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl3 = this.@__BuildControl__control28();
            
            #line default
            #line hidden
            
            #line 304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control24() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control25), null);
            
            #line default
            #line hidden
            
            #line 304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.HeaderText = "Action";
            
            #line default
            #line hidden
            
            #line 304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control8(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.TemplateField @__ctrl1;
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl1 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl2;
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl2 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl3;
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl3 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl4;
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl4 = this.@__BuildControl__control24();
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlGvCategory() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            
            #line default
            #line hidden
            this.GvCategory = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ID = "GvCategory";
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.CssClass = "table table-striped table-bordered nowrap";
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.AutoGenerateColumns = false;
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.DataKeyNames = new string[] {
                    "id"};
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.AllowPaging = false;
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.ShowHeader = true;
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.PageSize = 50;
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            this.@__BuildControl__control8(@__ctrl.Columns);
            
            #line default
            #line hidden
            
            #line 283 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.RowCommand += new System.Web.UI.WebControls.GridViewCommandEventHandler(this.GvCategory_RowCommand);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10248,
                        2785,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control29() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                                <div id=""DivFooterRow"" style=""overflow: hidden"">
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13033,
                        338,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control30() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"

                                    <br />
                                    <br />
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                </div>
            </div>
        </div>
    </div>

    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13386,
                        334,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control31() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n   ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13745,
                        5,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control32() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        13985,
                        8,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control33() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        22188,
                        2,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl2;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl2 = this.@__BuildControlToolkitScriptManager1();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl3 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl4;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl4 = this.@__BuildControltxtcnamefilter();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl5 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::AjaxControlToolkit.AutoCompleteExtender @__ctrl6;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl6 = this.@__BuildControlAutoCompleteExtender1();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl7 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl8;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl8 = this.@__BuildControlbtnresetfilter();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl9 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl10;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl10 = this.@__BuildControlGvCategory();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl11 = this.@__BuildControl__control29();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl12;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl12 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl13 = this.@__BuildControl__control31();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl14;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl14 = this.@__BuildControl__control32();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl15 = this.@__BuildControl__control33();
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_categorylist_aspx @__ctrl) {
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__ctrl.MasterPageFile = "~/Admin/AdminMasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 5 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 232 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\CategoryList.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_categorylist_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 455824712;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
