#pragma checksum "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5047C00BAAC667695803042ECF535A1FBEE49AB4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Admin_Addenquiry : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 69 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
    
    #line default
    #line hidden
    
    
    #line 72 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::System.Web.UI.WebControls.HiddenField HFccode;
    
    #line default
    #line hidden
    
    
    #line 73 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::System.Web.UI.WebControls.HiddenField HFcname;
    
    #line default
    #line hidden
    
    
    #line 75 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::System.Web.UI.WebControls.HiddenField hfregby;
    
    #line default
    #line hidden
    
    
    #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtcname;
    
    #line default
    #line hidden
    
    
    #line 115 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
    
    #line default
    #line hidden
    
    
    #line 117 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::AjaxControlToolkit.AutoCompleteExtender AutoCompleteExtender1;
    
    #line default
    #line hidden
    
    
    #line 122 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::System.Web.UI.WebControls.Label lblmsg;
    
    #line default
    #line hidden
    
    
    #line 137 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::System.Web.UI.WebControls.FileUpload FileUpload1;
    
    #line default
    #line hidden
    
    
    #line 146 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::System.Web.UI.WebControls.TextBox txtremark;
    
    #line default
    #line hidden
    
    
    #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::System.Web.UI.WebControls.Button btnadd;
    
    #line default
    #line hidden
    
    
    #line 171 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    protected global::System.Web.UI.WebControls.Button btnreset;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected ASP.global_asax ApplicationInstance {
        get {
            return ((ASP.global_asax)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    using AjaxControlToolkit;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 4 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class admin_addenquiry_aspx : global::Admin_Addenquiry, System.Web.IHttpHandler {
        
        private static System.Reflection.MethodInfo @__PageInspector_SetTraceDataMethod = global::ASP.admin_addenquiry_aspx.@__PageInspector_LoadHelper("SetTraceData");
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public admin_addenquiry_aspx() {
            string[] dependencies;
            
            #line 912304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/Admin/Addenquiry.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.admin_addenquiry_aspx.@__initialized == false)) {
                global::ASP.admin_addenquiry_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/Admin/Addenquiry.aspx";
                dependencies[1] = "~/Admin/AdminMasterPage.master";
                dependencies[2] = "~/Admin/AdminMasterPage.master.cs";
                dependencies[3] = "~/Admin/Addenquiry.aspx.cs";
                global::ASP.admin_addenquiry_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.admin_addenquiry_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control2() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
    <style>
        .spancls {
            color: #5d5656 !important;
            font-size: 13px !important;
            font-weight: 600;
            text-align: left;
        }

        .starcls {
            color: red;
            font-size: 18px;
            font-weight: 700;
        }

        .card .card-header span {
            color: #060606;
            display: block;
            font-size: 13px;
            margin-top: 5px;
        }

        .errspan {
            float: right;
            margin-right: 6px;
            margin-top: -25px;
            position: relative;
            z-index: 2;
            color: black;
        }

        .currentlbl {
            text-align: center !important;
        }

        .completionList {
            border: solid 1px Gray;
            border-radius: 5px;
            margin: 0px;
            padding: 3px;
            height: 120px;
            overflow: auto;
            background-color: #FFFFFF;
        }

        .listItem {
            color: #191919;
        }

        .itemHighlighted {
            background-color: #ADD6FF;
        }
         .reqcls {
            color: red;
            font-weight: 600;
            font-size: 14px;
        }
         .aspNetDisabled{
             cursor:not-allowed !important;
         }
    </style>
");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        335,
                        1382,
                        true});
            return @__ctrl;
        }
        
        private static System.Reflection.MethodInfo @__PageInspector_LoadHelper(string helperName) {
            System.Type helperClass = System.Type.GetType("Microsoft.VisualStudio.Web.PageInspector.Runtime.WebForms.TraceHelpers, Microsoft" +
                    ".VisualStudio.Web.PageInspector.Tracing, Version=15.0.0.0, Culture=neutral, Publ" +
                    "icKeyToken=b03f5f7f11d50a3a", false, false);
            if ((helperClass != null)) {
                return helperClass.GetMethod(helperName);
            }
            return null;
        }
        
        private void @__PageInspector_SetTraceData(object[] parameters) {
            if ((global::ASP.admin_addenquiry_aspx.@__PageInspector_SetTraceDataMethod != null)) {
                global::ASP.admin_addenquiry_aspx.@__PageInspector_SetTraceDataMethod.Invoke(null, parameters);
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent1(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 6 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 6 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control3() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1818,
                        6,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.ToolkitScriptManager @__BuildControlToolkitScriptManager1() {
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl;
            
            #line 69 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::AjaxControlToolkit.ToolkitScriptManager();
            
            #line default
            #line hidden
            this.ToolkitScriptManager1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 69 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "ToolkitScriptManager1";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1824,
                        95,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control4() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    <div class=\"page-wrapper\">\r\n        <div class=\"page-body\">\r\n            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1919,
                        79,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlHFccode() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            
            #line 72 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            
            #line default
            #line hidden
            this.HFccode = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 72 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "HFccode";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        1998,
                        47,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control5() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2045,
                        14,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlHFcname() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            
            #line 73 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            
            #line default
            #line hidden
            this.HFcname = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 73 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "HFcname";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2059,
                        47,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control6() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n           \r\n            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2106,
                        27,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhfregby() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            
            #line 75 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            
            #line default
            #line hidden
            this.hfregby = @__ctrl;
            @__ctrl.TemplateControl = this;
            
            #line 75 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "hfregby";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2133,
                        47,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control7() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n\r\n\r\n            <div class=\"row\">\r\n                <div class=\"col-md-7\">\r\n    " +
                    "                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2180,
                        97,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control8() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                </div>


                <div class=""col-md-5"">
                    <div class=""page-header-breadcrumb"">
                        <div style=""float: right; margin: 3px; margin-bottom: 5px;"">
                            <span><a href=""AllCompanyList.aspx"" style=""font-size: 16px; border: 1px dashed gray; padding: 4px;"">&nbsp;Company List</a>&nbsp;&nbsp;
                                <a href=""EnquiryList.aspx"" style=""font-size: 16px; border: 1px dashed gray; padding: 4px;"">&nbsp;Enquiry List</a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class=""container py-3"">
                <div class=""card"">
                    <div class=""card-header bg-primary text-uppercase text-white"">
                        <h5>Register an Enquiry</h5>
                    </div>
                    <div class=""row"">
                        <div class=""col-xl-12 col-md-12"">
                            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        2551,
                        1038,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control9() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                            <div class=""card-header"">
                                <div class=""row"">
                                    <div class=""col-md-12"">
                                        <br />
                                                <div class=""row""><div class=""col-md-2""></div>
                                                    <div class=""col-md-2 spancls"">Company Name<i class=""reqcls"">*&nbsp;</i> : </div>
                                                    <div class=""col-md-4"">
                                                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        3617,
                        578,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtcname() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtcname = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "txtcname";
            
            #line default
            #line hidden
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.AutoPostBack = true;
            
            #line default
            #line hidden
            
            #line 114 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.TextChanged += new System.EventHandler(this.txtcname_TextChanged);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4195,
                        150,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control10() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4345,
                        58,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator1() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 115 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 115 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "RequiredFieldValidator1";
            
            #line default
            #line hidden
            
            #line 115 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 115 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ErrorMessage = "Please Enter Company Name";
            
            #line default
            #line hidden
            
            #line 115 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ControlToValidate = "txtcname";
            
            #line default
            #line hidden
            
            #line 115 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 115 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 115 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4403,
                        313,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control11() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4716,
                        58,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.AutoCompleteExtender @__BuildControlAutoCompleteExtender1() {
            global::AjaxControlToolkit.AutoCompleteExtender @__ctrl;
            
            #line 117 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::AjaxControlToolkit.AutoCompleteExtender();
            
            #line default
            #line hidden
            this.AutoCompleteExtender1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 117 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "AutoCompleteExtender1";
            
            #line default
            #line hidden
            
            #line 117 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.CompletionListCssClass = "completionList";
            
            #line default
            #line hidden
            
            #line 117 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.CompletionListHighlightedItemCssClass = "itemHighlighted";
            
            #line default
            #line hidden
            
            #line 117 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.CompletionListItemCssClass = "listItem";
            
            #line default
            #line hidden
            
            #line 117 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.CompletionInterval = 10;
            
            #line default
            #line hidden
            
            #line 117 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.MinimumPrefixLength = 1;
            
            #line default
            #line hidden
            
            #line 117 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ServiceMethod = "GetCompanyList";
            
            #line default
            #line hidden
            
            #line 117 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.TargetControlID = "txtcname";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        4774,
                        576,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control12() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5350,
                        58,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Label @__BuildControllblmsg() {
            global::System.Web.UI.WebControls.Label @__ctrl;
            
            #line 122 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Label();
            
            #line default
            #line hidden
            this.lblmsg = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 122 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "lblmsg";
            
            #line default
            #line hidden
            
            #line 122 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.Text = "";
            
            #line default
            #line hidden
            
            #line 122 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 122 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.Visible = false;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5408,
                        90,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control13() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                    </div>\r\n                   " +
                    "                                 ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        5498,
                        114,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control14() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                                </div>
                                        

                                        <br />
                                        <div class=""row""><div class=""col-md-2""></div>
                                            <div class=""col-md-2 spancls"">File : </div>
                                            <div class=""col-md-4"">
                                                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6378,
                        442,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlFileUpload1() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            
            #line 137 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            
            #line default
            #line hidden
            this.FileUpload1 = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 137 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "FileUpload1";
            
            #line default
            #line hidden
            
            #line 137 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6820,
                        74,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control15() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                            </div>
                                            
                                        </div>

                                        <br />
                                        <div class=""row""><div class=""col-md-2""></div>
                                            <div class=""col-md-2 spancls"">Remark : </div>
                                            <div class=""col-md-4"">
                                                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        6894,
                        492,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltxtremark() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 146 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.txtremark = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 146 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "txtremark";
            
            #line default
            #line hidden
            
            #line 146 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.CssClass = "form-control";
            
            #line default
            #line hidden
            
            #line 146 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.MultiLine;
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7386,
                        102,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control16() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                                ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7488,
                        50,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control17() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                                            </div>\r\n                           " +
                    "             </div>\r\n\r\n                                         ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        7856,
                        145,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control18() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"
                                        

                                        <br /><br />
                                        <div class=""row"">
                                            <div class=""col-md-4""></div>
                                            <div class=""col-md-2"">
                                                <center> ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        8960,
                        358,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnadd() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnadd = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "btnadd";
            
            #line default
            #line hidden
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ValidationGroup = "form1";
            
            #line default
            #line hidden
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.CssClass = "btn btn-primary";
            
            #line default
            #line hidden
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.Text = "Add Enquiry";
            
            #line default
            #line hidden
            
            #line 168 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnadd_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9318,
                        146,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control19() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("</center>\r\n                                            </div>\r\n                  " +
                    "                          <div class=\"col-md-2\">\r\n                              " +
                    "                  <center> ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9464,
                        188,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnreset() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 171 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.btnreset = @__ctrl;
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 171 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.ID = "btnreset";
            
            #line default
            #line hidden
            
            #line 171 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.CssClass = "btn btn-danger";
            
            #line default
            #line hidden
            
            #line 171 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 171 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.Text = "Reset";
            
            #line default
            #line hidden
            
            #line 171 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.Click += new System.EventHandler(this.btnreset_Click);
            
            #line default
            #line hidden
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9652,
                        119,
                        false});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control20() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl(@"</center>
                                            </div>
                                            <div class=""col-md-6""></div>

                                        </div>
                                        <br />

                                    </div>
                                </div>


                            </div>
                            ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        9771,
                        389,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control21() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                        </div>\r\n                    </div>\r\n\r\n                 " +
                    "   ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10175,
                        84,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control22() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n                </div>\r\n            </div>\r\n        </div>\r\n        ");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10274,
                        70,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.LiteralControl @__BuildControl__control23() {
            global::System.Web.UI.LiteralControl @__ctrl;
            @__ctrl = new global::System.Web.UI.LiteralControl("\r\n    </div>\r\n\r\n\r\n\r\n\r\n");
            @__ctrl.TemplateControl = this;
            this.@__PageInspector_SetTraceData(new object[] {
                        @__ctrl,
                        null,
                        10359,
                        22,
                        true});
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlContent2(System.Web.UI.Control @__ctrl) {
            global::System.Web.UI.LiteralControl @__ctrl1;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl2;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl2 = this.@__BuildControlToolkitScriptManager1();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl3;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl3 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HiddenField @__ctrl4;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl4 = this.@__BuildControlHFccode();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl5;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl5 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HiddenField @__ctrl6;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl6 = this.@__BuildControlHFcname();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl7;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl7 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HiddenField @__ctrl8;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl8 = this.@__BuildControlhfregby();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl9;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl9 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl10;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl10 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl11;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl11 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl12;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl12 = this.@__BuildControltxtcname();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl13;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl13 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl14;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl14 = this.@__BuildControlRequiredFieldValidator1();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl15;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl15 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            global::AjaxControlToolkit.AutoCompleteExtender @__ctrl16;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl16 = this.@__BuildControlAutoCompleteExtender1();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl17;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl17 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Label @__ctrl18;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl18 = this.@__BuildControllblmsg();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl19;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl19 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl20;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl20 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl20);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.FileUpload @__ctrl21;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl21 = this.@__BuildControlFileUpload1();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl21);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl22;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl22 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl22);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl23;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl23 = this.@__BuildControltxtremark();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl23);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl24;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl24 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl24);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl25;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl25 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl25);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl26;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl26 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl26);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl27;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl27 = this.@__BuildControlbtnadd();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl27);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl28;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl28 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl28);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl29;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl29 = this.@__BuildControlbtnreset();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl29);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl30;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl30 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl30);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl31;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl31 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl31);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl32;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl32 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl32);
            
            #line default
            #line hidden
            global::System.Web.UI.LiteralControl @__ctrl33;
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl33 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(@__ctrl33);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(admin_addenquiry_aspx @__ctrl) {
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.Title = "";
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__ctrl.MasterPageFile = "~/Admin/AdminMasterPage.master";
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            
            #line 6 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            this.AddContentTemplate("head", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent1)));
            
            #line default
            #line hidden
            
            #line 68 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            this.AddContentTemplate("ContentPlaceHolder1", new System.Web.UI.CompiledTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControlContent2)));
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n"));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "E:\Ashish\User Autorization Excel Enc 21-11-22\Admin\Addenquiry.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.admin_addenquiry_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.admin_addenquiry_aspx.@__fileDependencies);
            this.Request.ValidateInput();
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1972921398;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
